# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				slime = true
				villager = true
				sheep = true
				polar_bear = true
				glow_squid = true
				item = true
				pig = true
				cat = true
				iron_golem = true
				skeleton = true
				drowned = true
				salmon = true
				bat = true
				zombie = true
				squid = true
				horse = true
				cow = true
				chicken = true
				creeper = true
				enderman = true
				spider = true
				bee = true
				zombie_villager = true
				item_frame = true
				wolf = true
				witch = true
				chest_minecart = true
				armor_stand = true
				piglin_brute = true
				dolphin = true
				cod = true
				phantom = true
				firework_rocket = true
				goat = true
				rabbit = true
				donkey = true
				pillager = true
				potion = true
				arrow = true
				silverfish = true
				guardian = true
				turtle = true
				axolotl = true
				tnt_minecart = true
				experience_orb = true
				pufferfish = true
				tropical_fish = true
				parrot = true
				ocelot = true
				piglin = true
				vindicator = true
				fox = true
				wither = true
				wither_skull = true
				boat = true
				egg = true
				trident = true
				elder_guardian = true
				evoker = true
				mooshroom = true
				llama = true
				husk = true
				lightning_bolt = true
				zombified_piglin = true
				painting = true
				area_effect_cloud = true
				wandering_trader = true
				trader_llama = true
				stray = true
				illusioner = true
				eye_of_ender = true
				snow_golem = true
				snowball = true
				cave_spider = true

			[light_sources.settings.entities.immersive_aircraft]
				biplane = true
				cargo_airship = true
				quadrocopter = true
				gyrodyne = true
				airship = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				moobloom = true
				glare = true
				mauler = true

			[light_sources.settings.entities.sit]
				entity_sit = true

			[light_sources.settings.entities.hwg]
				merc = true
				bullets = true
				spy = true
				grenade = true
				mbullets = true
				technodemon_greater_1 = true
				shell = true
				fireball = true
				blazerod = true
				rockets = true
				technodemon_lesser_1 = true
				flame_firing = true

			[light_sources.settings.entities.smallships]
				drakkar = true
				brigg = true

			[light_sources.settings.entities.mtmechs]
				magitekarmor = true
				protoarmor = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_skeleton = true
				mutant_zombie = true
				mutant_creeper = true
				mutant_arrow = true
				creeper_minion = true
				throwable_block = true
				mutant_enderman = true
				endersoul_fragment = true
				mutant_snow_golem = true
				spider_pig = true
				endersoul_clone = true

			[light_sources.settings.entities.valkyrienskies]
				ship_mounting_entity = true

			[light_sources.settings.entities.aqupd]
				grizzly_bear = true

			[light_sources.settings.entities.grapplemod]
				grapplehook = true

			[light_sources.settings.entities.arcanus]
				magic_missile = true
				arcane_barrier = true

			[light_sources.settings.entities.requiem]
				player_shell = true

			[light_sources.settings.entities.fishofthieves]
				plentifin = true
				wildsplash = true
				splashtail = true
				ancientscale = true
				islehopper = true
				pondie = true
				stormfish = true
				devilfish = true
				wrecker = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.naturalist]
				firefly = true
				snake = true
				boar = true
				giraffe = true
				butterfly = true
				robin = true
				deer = true
				bear = true
				cardinal = true
				snail = true
				canary = true
				bluejay = true

			[light_sources.settings.entities.xercapaint]
				easel = true

			[light_sources.settings.entities.xercamusic]
				music_spirit = true

			[light_sources.settings.entities.scooters]
				electric_scooter = true
				kick_scooter = true

			[light_sources.settings.entities.musketmod]
				bullet = true

			[light_sources.settings.entities.ygm76]
				bullet = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.niftycarts]
				supply_cart = true
				plow = true
				animal_cart = true
				postilion = true

