#Configuration to disable the rendering of certain supplies in the supply cart
#Enables/Disables the rendering of all supplies
render_supplies = true
#Falls back to rendering as items if false
render_supply_gear = true
#Falls back to rendering as items if false
render_supply_flowers = true
#Falls back to rendering as items if false
render_supply_paintings = true
#Falls back to rendering as items if false
render_supply_wheel = true
